### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by jqueguiner** [ElementAI/HighRes-net#1]
Even by reducing the batch size the fusion model doesn't fit into a 16G GPU.

I tried also to split the RecuversiveNet fuse onto the first 16GB GPUGPUID 0 and get it into the forward pass with GPUID 1.

but tensor needs to be collocated.
Can you help me either reduce the mem issue to fit into a 16G GPU or split the computation accross multi devices ?

thanks a lot

**Comment by alkalait** [comment]
Have you tried reducing the number of views?

Have a look at the table in the [README](https://github.com/ElementAI/HighRes-net#a-recipe-to-enhance-the-vision-of-the-esa-satellite-proba-v)

Increased batch size will buy you more, whereas 32 views has diminished returns compared to 16.

**Comment by jqueguiner** [comment]
Yes, already tried that :

  "training": {
     "num_epochs": 400,
     "batch_size": 16,

     "min_L": 32,
     "n_views": 4,
     "n_workers": 4,
     "crop": 3,


     "lr": 0.0007,
     "lr_step": 2,
     "lr_decay": 0.97,

     "load_lr_maps": false,
     "beta": 50.0,

    "create_patches": false,
    "patch_size": 64,
    "val_proportion": 0.10,
    "lambda": 0.000001
  }

gives 
RuntimeError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 15.75 GiB total capacity; 14.27 GiB already allocated; 433.56 MiB free; 1.16 MiB cached)
while GPU mem was flushed just before the experiment

**Comment by ilkarman** [comment]
On a 16GB P100 I've found that I need batch and views to be 4 (rather than 32) to fit into memory. I'm not sure why? The model itself loaded on GPU takes up around 1GB. The code doesn't mention training in half-precision either so it's interesting that the 32GB V100s fit batch=32, views=32.

**Comment by ilkarman** [comment]
Would you also decrease min_L (minimum number of views) to match n_views? On a 16GB P100 I can just about squeeze into memory: batch=8, min_L=16 n_views=16 (but not if min_L=32)

**Comment by alkalait** [comment]
That's right.

- `min_L` acts as a lower-bound on the views always present. If the input  has views fewer than `min_L` then it will be padded to `min_L` with dummy views (`0`-padding).

- `n_views` : the number of LR views _randomly_* selected from the LR pool of a site.

For instance, what you want to avoid is `n_views = 16` and `min_L = 32` as that would always `0`-pad your views to 32.

_* views with larger clearance are more likely to be selected_

**Comment by ilkarman** [comment]
Freddie, also the [create_patches = false in the config](https://github.com/ElementAI/HighRes-net/issues/2#issuecomment-512412189) natually increases the memory usage.

With create_patches = true; I can run batch-size 32 with min_l and n_views = 16, which matches your memory usage predictions table.

**Comment by alkalait** [comment]
Indeed. That flag somehow flew under our radar!

**Comment by jqueguiner** [comment]
GG @ilkarman
